/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package SCREENS;

import MAIN.Main;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author olf5jvl
 */
public class Cracha_Hrl extends javax.swing.JDialog {

    private DefaultTableModel tabela;
    /**
     * Creates new form 
     */
    public Cracha_Hrl(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initTableListener();
        tabela = (DefaultTableModel) jTBadgeTable.getModel();
        tabela.setNumRows(0);
        tabela.addRow(new Object[]{"01234","UNUSED","-"});
        tabela.addRow(new Object[]{"01232","IN USE","Leandro Paulo da Silva"});
        tabela.addRow(new Object[]{"01222","IN USE","Fernando da Silva de Oliveira"});
        tabela.addRow(new Object[]{"01235","UNUSED","-"});
        filterBadgeTable(0);
    }

    private void addBadgeInTable(){
        // Atribui informações de teste na tabela
        if(!isIdDuplicate(jTCreateBadge.getText()))
            tabela.addRow(new Object[]{jTCreateBadge.getText(),"UNUSED","-"});
        else{
            System.out.println("Dados duplicados");
        }
    }
    
    private void filterBadgeTable(int n){
        
        TableRowSorter sorter = new TableRowSorter(tabela);
        jTBadgeTable.setRowSorter(sorter);
        
        String filter = "";
        
        switch(n){
            case 2 -> filter = "IN USE";
            case 3 -> filter = "UNUSED";
        }
        RowFilter<Object, Object> rowFilter = RowFilter.regexFilter(filter, 1);
        sorter.setRowFilter(rowFilter);
    }
    
    private void initTableListener() {
        jTBadgeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = jTBadgeTable.getSelectedRow();
                if (selectedRow != -1) {
                    jTChangeBadgeCode.setText(jTBadgeTable.getValueAt(selectedRow, 0).toString());
                    jTChangeBadgeOwner.setText(jTBadgeTable.getValueAt(selectedRow, 2).toString());
                    
                    jTAssociateBadgeCode.setText(jTBadgeTable.getValueAt(selectedRow, 0).toString());
                    
                    //ele puxará da tabela ou de colaborador, ou de terceirizado
                    //jTAssociateBadgeOwner.setText(jTBadgeTable.getValueAt(selectedRow, 2).toString());
                }
            }
        });
    }
    
    private boolean isIdDuplicate(String id) {
        // Recupera os IDs existentes
        int rowCount = tabela.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            String existingId = (String) tabela.getValueAt(i, 0); // Assume que ID está na primeira coluna
            if (id.equals(existingId)) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTBadgeTable = new javax.swing.JTable();
        jPOptionsContainer = new javax.swing.JPanel();
        jBAssociateBadge = new javax.swing.JButton();
        jBCreateBadge = new javax.swing.JButton();
        jBChangeBadge = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPOptionBox = new javax.swing.JPanel();
        jPCreateBadgePainel = new javax.swing.JPanel();
        jLCreateLabel = new javax.swing.JLabel();
        jTCreateBadge = new javax.swing.JTextField();
        jBCreateBadgeConfirm = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPChangeBadgePainel = new javax.swing.JPanel();
        jLChangeLabel = new javax.swing.JLabel();
        jTChangeBadgeOwner = new javax.swing.JTextField();
        jTChangeBadgeCode = new javax.swing.JTextField();
        jBChangeBadgeConfirm = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPAssociateBadgePainel = new javax.swing.JPanel();
        jLAssociateLabel = new javax.swing.JLabel();
        jTAssociateBadgeOwner = new javax.swing.JTextField();
        jBAssociateBadgeConfirm = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTAssociateBadgeCode = new javax.swing.JTextField();
        jBBack = new javax.swing.JButton();
        jPHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1140, 730));
        setMinimumSize(new java.awt.Dimension(1120, 730));
        setPreferredSize(new java.awt.Dimension(1120, 730));
        setResizable(false);

        jPContainer.setBackground(new java.awt.Color(224, 226, 229));
        jPContainer.setMaximumSize(new java.awt.Dimension(0, 0));
        jPContainer.setMinimumSize(new java.awt.Dimension(0, 0));
        jPContainer.setPreferredSize(new java.awt.Dimension(0, 0));

        jTBadgeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Status", "Owner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBadgeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTBadgeTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBAssociateBadge.setBackground(new java.awt.Color(0, 110, 173));
        jBAssociateBadge.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jBAssociateBadge.setForeground(new java.awt.Color(255, 255, 255));
        jBAssociateBadge.setText("Associate");
        jBAssociateBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAssociateBadgeActionPerformed(evt);
            }
        });

        jBCreateBadge.setBackground(new java.awt.Color(0, 110, 173));
        jBCreateBadge.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jBCreateBadge.setForeground(new java.awt.Color(255, 255, 255));
        jBCreateBadge.setText("Create");
        jBCreateBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateBadgeActionPerformed(evt);
            }
        });

        jBChangeBadge.setBackground(new java.awt.Color(0, 110, 173));
        jBChangeBadge.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jBChangeBadge.setForeground(new java.awt.Color(255, 255, 255));
        jBChangeBadge.setText("Change");
        jBChangeBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChangeBadgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOptionsContainerLayout = new javax.swing.GroupLayout(jPOptionsContainer);
        jPOptionsContainer.setLayout(jPOptionsContainerLayout);
        jPOptionsContainerLayout.setHorizontalGroup(
            jPOptionsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOptionsContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jBCreateBadge, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jBChangeBadge, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jBAssociateBadge, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPOptionsContainerLayout.setVerticalGroup(
            jPOptionsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOptionsContainerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPOptionsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCreateBadge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBChangeBadge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAssociateBadge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jLabel2.setText("Select an Option for Badge");

        jLabel4.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jLabel4.setText("Badge");

        jPOptionBox.setMaximumSize(new java.awt.Dimension(490, 140));
        jPOptionBox.setMinimumSize(new java.awt.Dimension(490, 140));

        jPCreateBadgePainel.setMaximumSize(new java.awt.Dimension(478, 120));
        jPCreateBadgePainel.setMinimumSize(new java.awt.Dimension(478, 120));
        jPCreateBadgePainel.setPreferredSize(new java.awt.Dimension(478, 120));

        jLCreateLabel.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jLCreateLabel.setText("Insert the Badge code");

        jTCreateBadge.setFont(new java.awt.Font("Bosch Sans", 0, 14)); // NOI18N
        jTCreateBadge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCreateBadgeKeyTyped(evt);
            }
        });

        jBCreateBadgeConfirm.setBackground(new java.awt.Color(0, 110, 173));
        jBCreateBadgeConfirm.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jBCreateBadgeConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jBCreateBadgeConfirm.setText("Confirm");
        jBCreateBadgeConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateBadgeConfirmActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bosch Sans", 0, 10)); // NOI18N
        jLabel5.setText("Code");

        javax.swing.GroupLayout jPCreateBadgePainelLayout = new javax.swing.GroupLayout(jPCreateBadgePainel);
        jPCreateBadgePainel.setLayout(jPCreateBadgePainelLayout);
        jPCreateBadgePainelLayout.setHorizontalGroup(
            jPCreateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCreateBadgePainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCreateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCreateLabel)
                    .addGroup(jPCreateBadgePainelLayout.createSequentialGroup()
                        .addComponent(jTCreateBadge, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBCreateBadgeConfirm))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPCreateBadgePainelLayout.setVerticalGroup(
            jPCreateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCreateBadgePainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCreateLabel)
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCreateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCreateBadge, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCreateBadgeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPOptionBoxLayout = new javax.swing.GroupLayout(jPOptionBox);
        jPOptionBox.setLayout(jPOptionBoxLayout);
        jPOptionBoxLayout.setHorizontalGroup(
            jPOptionBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOptionBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCreateBadgePainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPOptionBoxLayout.setVerticalGroup(
            jPOptionBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOptionBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCreateBadgePainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPChangeBadgePainel.setMaximumSize(new java.awt.Dimension(478, 120));
        jPChangeBadgePainel.setMinimumSize(new java.awt.Dimension(478, 120));
        jPChangeBadgePainel.setPreferredSize(new java.awt.Dimension(478, 120));

        jLChangeLabel.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jLChangeLabel.setText("Remove Badge From");

        jTChangeBadgeOwner.setFont(new java.awt.Font("Bosch Sans", 0, 14)); // NOI18N
        jTChangeBadgeOwner.setEnabled(false);

        jTChangeBadgeCode.setFont(new java.awt.Font("Bosch Sans", 0, 14)); // NOI18N
        jTChangeBadgeCode.setEnabled(false);

        jBChangeBadgeConfirm.setBackground(new java.awt.Color(0, 110, 173));
        jBChangeBadgeConfirm.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jBChangeBadgeConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jBChangeBadgeConfirm.setText("Confirm");
        jBChangeBadgeConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChangeBadgeConfirmActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bosch Sans", 0, 10)); // NOI18N
        jLabel6.setText("Code");

        jLabel7.setFont(new java.awt.Font("Bosch Sans", 0, 10)); // NOI18N
        jLabel7.setText("Owner");

        javax.swing.GroupLayout jPChangeBadgePainelLayout = new javax.swing.GroupLayout(jPChangeBadgePainel);
        jPChangeBadgePainel.setLayout(jPChangeBadgePainelLayout);
        jPChangeBadgePainelLayout.setHorizontalGroup(
            jPChangeBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPChangeBadgePainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPChangeBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLChangeLabel)
                    .addGroup(jPChangeBadgePainelLayout.createSequentialGroup()
                        .addGroup(jPChangeBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTChangeBadgeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPChangeBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPChangeBadgePainelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPChangeBadgePainelLayout.createSequentialGroup()
                                .addComponent(jTChangeBadgeOwner, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBChangeBadgeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPChangeBadgePainelLayout.setVerticalGroup(
            jPChangeBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPChangeBadgePainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLChangeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPChangeBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPChangeBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTChangeBadgeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTChangeBadgeOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBChangeBadgeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPAssociateBadgePainel.setMaximumSize(new java.awt.Dimension(478, 120));
        jPAssociateBadgePainel.setMinimumSize(new java.awt.Dimension(478, 120));
        jPAssociateBadgePainel.setPreferredSize(new java.awt.Dimension(478, 120));

        jLAssociateLabel.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jLAssociateLabel.setText("Associate badge To");

        jTAssociateBadgeOwner.setFont(new java.awt.Font("Bosch Sans", 0, 14)); // NOI18N
        jTAssociateBadgeOwner.setEnabled(false);

        jBAssociateBadgeConfirm.setBackground(new java.awt.Color(0, 110, 173));
        jBAssociateBadgeConfirm.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jBAssociateBadgeConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jBAssociateBadgeConfirm.setText("Confirm");
        jBAssociateBadgeConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAssociateBadgeConfirmActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bosch Sans", 0, 10)); // NOI18N
        jLabel9.setText("Owner");

        jLabel8.setFont(new java.awt.Font("Bosch Sans", 0, 10)); // NOI18N
        jLabel8.setText("Code");

        jTAssociateBadgeCode.setFont(new java.awt.Font("Bosch Sans", 0, 14)); // NOI18N
        jTAssociateBadgeCode.setEnabled(false);

        javax.swing.GroupLayout jPAssociateBadgePainelLayout = new javax.swing.GroupLayout(jPAssociateBadgePainel);
        jPAssociateBadgePainel.setLayout(jPAssociateBadgePainelLayout);
        jPAssociateBadgePainelLayout.setHorizontalGroup(
            jPAssociateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAssociateBadgePainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAssociateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAssociateBadgePainelLayout.createSequentialGroup()
                        .addComponent(jLAssociateLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPAssociateBadgePainelLayout.createSequentialGroup()
                        .addGroup(jPAssociateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTAssociateBadgeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPAssociateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAssociateBadgePainelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPAssociateBadgePainelLayout.createSequentialGroup()
                                .addComponent(jTAssociateBadgeOwner, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAssociateBadgeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPAssociateBadgePainelLayout.setVerticalGroup(
            jPAssociateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAssociateBadgePainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAssociateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAssociateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAssociateBadgePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTAssociateBadgeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAssociateBadgeOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAssociateBadgeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jBBack.setBackground(new java.awt.Color(0, 110, 173));
        jBBack.setFont(new java.awt.Font("Bosch Sans", 0, 18)); // NOI18N
        jBBack.setForeground(new java.awt.Color(255, 255, 255));
        jBBack.setText("Back");
        jBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPContainerLayout = new javax.swing.GroupLayout(jPContainer);
        jPContainer.setLayout(jPContainerLayout);
        jPContainerLayout.setHorizontalGroup(
            jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContainerLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(351, 351, 351))
            .addGroup(jPContainerLayout.createSequentialGroup()
                .addGroup(jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPChangeBadgePainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPAssociateBadgePainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPContainerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPOptionsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPOptionBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPContainerLayout.setVerticalGroup(
            jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPContainerLayout.createSequentialGroup()
                            .addComponent(jPOptionsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPOptionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205)
                .addGroup(jPContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPChangeBadgePainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPAssociateBadgePainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPHeader.setBackground(new java.awt.Color(239, 241, 242));
        jPHeader.setMaximumSize(new java.awt.Dimension(0, 0));
        jPHeader.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/header-bosch.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPHeaderLayout = new javax.swing.GroupLayout(jPHeader);
        jPHeader.setLayout(jPHeaderLayout);
        jPHeaderLayout.setHorizontalGroup(
            jPHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHeaderLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPHeaderLayout.setVerticalGroup(
            jPHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
            .addComponent(jPHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCreateBadgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCreateBadgeKeyTyped
        String badgeCode = jTCreateBadge.getText();
        if(badgeCode.length()>4){
            badgeCode =badgeCode.substring(0,4);
        }
        jTCreateBadge.setText(badgeCode);
    }//GEN-LAST:event_jTCreateBadgeKeyTyped

    private void jBChangeBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChangeBadgeActionPerformed
        jTChangeBadgeCode.setText("");
        jTChangeBadgeOwner.setText("");
        
        jPCreateBadgePainel.setVisible(false);
        jPChangeBadgePainel.setVisible(true);
        jPAssociateBadgePainel.setVisible(false);
        filterBadgeTable(2);
    }//GEN-LAST:event_jBChangeBadgeActionPerformed

    private void jBCreateBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateBadgeActionPerformed
        jPCreateBadgePainel.setVisible(true);
        jPChangeBadgePainel.setVisible(false);
        jPAssociateBadgePainel.setVisible(false);
        filterBadgeTable(1);
    }//GEN-LAST:event_jBCreateBadgeActionPerformed

    private void jBAssociateBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAssociateBadgeActionPerformed
        jTAssociateBadgeCode.setText("");
        jTAssociateBadgeOwner.setText("");
        
        jPCreateBadgePainel.setVisible(false);
        jPChangeBadgePainel.setVisible(false);
        jPAssociateBadgePainel.setVisible(true);
        filterBadgeTable(3);
    }//GEN-LAST:event_jBAssociateBadgeActionPerformed

    private void jBChangeBadgeConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChangeBadgeConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBChangeBadgeConfirmActionPerformed

    private void jBCreateBadgeConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateBadgeConfirmActionPerformed
        if((jTCreateBadge.getText()).length()==5){
            addBadgeInTable();
        }
    }//GEN-LAST:event_jBCreateBadgeConfirmActionPerformed

    private void jBAssociateBadgeConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAssociateBadgeConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAssociateBadgeConfirmActionPerformed

    private void jBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackActionPerformed
        Main main = new Main(null,true);
        this.dispose();
        main.setVisible(true);
    }//GEN-LAST:event_jBBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cracha_Hrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cracha_Hrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cracha_Hrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cracha_Hrl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cracha_Hrl dialog = new Cracha_Hrl(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAssociateBadge;
    private javax.swing.JButton jBAssociateBadgeConfirm;
    private javax.swing.JButton jBBack;
    private javax.swing.JButton jBChangeBadge;
    private javax.swing.JButton jBChangeBadgeConfirm;
    private javax.swing.JButton jBCreateBadge;
    private javax.swing.JButton jBCreateBadgeConfirm;
    private javax.swing.JLabel jLAssociateLabel;
    private javax.swing.JLabel jLChangeLabel;
    private javax.swing.JLabel jLCreateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAssociateBadgePainel;
    private javax.swing.JPanel jPChangeBadgePainel;
    private javax.swing.JPanel jPContainer;
    private javax.swing.JPanel jPCreateBadgePainel;
    private javax.swing.JPanel jPHeader;
    private javax.swing.JPanel jPOptionBox;
    private javax.swing.JPanel jPOptionsContainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTAssociateBadgeCode;
    private javax.swing.JTextField jTAssociateBadgeOwner;
    private javax.swing.JTable jTBadgeTable;
    private javax.swing.JTextField jTChangeBadgeCode;
    private javax.swing.JTextField jTChangeBadgeOwner;
    private javax.swing.JTextField jTCreateBadge;
    // End of variables declaration//GEN-END:variables
}
